
GRANT REPLICATION SLAVE, REPLICATION CLIENT, REPLICATION SLAVE ADMIN, SUPER, RELOAD 
ON *.* TO 'maxscale_user'@'%' IDENTIFIED BY 'cH4JtWmDX7P';


GRANT REPLICATION SLAVE, REPLICATION CLIENT, REPLICATION SLAVE ADMIN, SUPER, RELOAD 
ON *.* TO 'repl'@'%' IDENTIFIED BY 'cH4JtWmDX7P';


GRANT REPLICATION SLAVE, REPLICATION CLIENT, REPLICATION SLAVE ADMIN, SUPER, RELOAD
ON *.* TO 'maxscale_mon'@'%' IDENTIFIED BY 'cH4JtWmDX7P';


-- 刷新权限
FLUSH PRIVILEGES;

-- 上面所有节点都需要执行

-- 下面从裤执行

CHANGE MASTER TO
  MASTER_HOST='103.219.192.202', # 主库IP
  MASTER_PORT=5306, 
  MASTER_USER='repl',
  MASTER_PASSWORD='cH4JtWmDX7P',
  MASTER_USE_GTID=current_pos;
START SLAVE;
